version: "3.4"                                                                                                        
                                                                                                                      
x-defaults: &defaults                                                                                                 
  restart: unless-stopped                                                                                             

services:
  server:
    build:
      context: .
      dockerfile: ./docker/dockerfile
    env_file:
     - ./docker/.env
    volumes:
      - ./:/app
    working_dir: /app